language: node_js

node_js:
  - 10.16.3
before_script:
  - npm install coverage
  - npm install -g nyc
script:
  - npm run lint
after_script:
  - npm run coverage
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT